package service_test

import (
	"bytes"
	"context"
	"errors"
	"io"
	"log/slog"
	"testing"
	"time"

	"github.com/anupam-chopra/prism/internal/cache"
	"github.com/anupam-chopra/prism/internal/cdn"
	"github.com/anupam-chopra/prism/internal/config"
	"github.com/anupam-chopra/prism/internal/model"
	"github.com/anupam-chopra/prism/internal/service"
	"github.com/anupam-chopra/prism/mock"
)

const testCloudFrontPrivateKey = `-----BEGIN PRIVATE KEY-----
MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAqjPwLqKGxkFi53dv
c8ywjTPKKnyFqrFr1kwVvNJzUR+zAm/gFnyVYC0lJMvV5cR41kO7ZvEZU72A42Im
idNpZQIDAQABAkAqNGTbe4vF/5LB6NjnMxuYd/4qmOQgVoxyAD3nq5vSwozDM33i
PJKWnuau4PXqlQBWBNWdVWqhLdFUpXk2FPfhAiEA32k79D9vZmUwvldTBz0PoIaD
8+vxN/Y8w4MqxLBwG/kCIQDDB8SsUB70nOr1Vo8d1xWNnG5z8Lhk9JTpQYxvKtfb
zQIgCEs+1413VETTb22MfotMxjfYNDkBJoO0s8lt0AmAz/kCID+1KemfwnzlRVsf
C2EUAVZg4zO8Tn+r5XjMkLM/q4OBAiEA2h349/JHm08Sor0Ude2tM0yJ+6XauucI
iTl48eFE6iQ=
-----END PRIVATE KEY-----`

type mockGenerator struct {
	output []byte
	err    error
	calls  int
}

func (g *mockGenerator) Generate(_ context.Context, _ *model.ManifestRequest) ([]byte, error) {
	g.calls++
	return g.output, g.err
}

func setupManifestService(t *testing.T) (*service.ManifestService, *mock.MockCache, *mockGenerator, *mockGenerator) {
	t.Helper()

	logger := slog.New(slog.NewTextHandler(io.Discard, nil))
	cfg := &config.Config{
		ManifestCacheTTL:     30,
		CloudFrontDomain:     "cdn.example.com",
		CloudFrontKeyPairID:  "KTEST123",
		CloudFrontPrivateKey: testCloudFrontPrivateKey,
	}
	cloudFront, err := cdn.NewCloudFront(cfg, logger)
	if err != nil {
		t.Fatalf("create CloudFront test client: %v", err)
	}

	cacheMock := mock.NewMockCache()
	hlsGen := &mockGenerator{output: []byte("#EXTM3U\nmanifest body")}
	dashGen := &mockGenerator{output: []byte(`<?xml version="1.0"?><MPD></MPD>`)}
	svc := service.NewManifestService(hlsGen, dashGen, cacheMock, cloudFront, cfg, logger)
	return svc, cacheMock, hlsGen, dashGen
}

func TestGetHLS_CacheHit(t *testing.T) {
	svc, cacheMock, hlsGen, _ := setupManifestService(t)
	req := &model.ManifestRequest{AssetID: "asset-1"}
	key := cache.ManifestKey("hls", req.AssetID, req.FilterHash())
	want := []byte("cached-hls-manifest")
	if err := cacheMock.Set(context.Background(), key, want, time.Minute); err != nil {
		t.Fatalf("seed cache: %v", err)
	}

	got, err := svc.GetHLS(context.Background(), req)
	if err != nil {
		t.Fatalf("GetHLS returned error: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("expected cached bytes %q, got %q", want, got)
	}
	if hlsGen.calls != 0 {
		t.Fatalf("expected generator not called, got %d calls", hlsGen.calls)
	}
}

func TestGetHLS_CacheMiss_GeneratesAndCaches(t *testing.T) {
	svc, cacheMock, hlsGen, _ := setupManifestService(t)
	req := &model.ManifestRequest{AssetID: "asset-1"}
	key := cache.ManifestKey("hls", req.AssetID, req.FilterHash())

	got, err := svc.GetHLS(context.Background(), req)
	if err != nil {
		t.Fatalf("GetHLS returned error: %v", err)
	}
	if !bytes.Equal(got, hlsGen.output) {
		t.Fatalf("expected generated bytes %q, got %q", hlsGen.output, got)
	}
	if hlsGen.calls != 1 {
		t.Fatalf("expected generator called once, got %d calls", hlsGen.calls)
	}
	cached, err := cacheMock.Get(context.Background(), key)
	if err != nil {
		t.Fatalf("expected cached manifest, got error: %v", err)
	}
	if !bytes.Equal(cached, hlsGen.output) {
		t.Fatalf("expected cached generated bytes %q, got %q", hlsGen.output, cached)
	}
}

func TestGetHLS_CacheSetFailure_DoesNotFailRequest(t *testing.T) {
	svc, cacheMock, hlsGen, _ := setupManifestService(t)
	cacheMock.SetFunc = func(_ context.Context, _ string, _ []byte, _ time.Duration) error {
		return errors.New("redis set failed")
	}
	req := &model.ManifestRequest{AssetID: "asset-1"}

	got, err := svc.GetHLS(context.Background(), req)
	if err != nil {
		t.Fatalf("expected manifest despite cache set failure, got error: %v", err)
	}
	if !bytes.Equal(got, hlsGen.output) {
		t.Fatalf("expected generated bytes %q, got %q", hlsGen.output, got)
	}
}

func TestGetHLS_GeneratorError(t *testing.T) {
	svc, _, hlsGen, _ := setupManifestService(t)
	hlsGen.err = errors.New("generator failed")
	req := &model.ManifestRequest{AssetID: "asset-1"}

	_, err := svc.GetHLS(context.Background(), req)
	if err == nil {
		t.Fatal("expected generator error")
	}
}

func TestGetDASH_CacheHit(t *testing.T) {
	svc, cacheMock, _, dashGen := setupManifestService(t)
	req := &model.ManifestRequest{AssetID: "asset-1"}
	key := cache.ManifestKey("dash", req.AssetID, req.FilterHash())
	want := []byte("cached-dash-manifest")
	if err := cacheMock.Set(context.Background(), key, want, time.Minute); err != nil {
		t.Fatalf("seed cache: %v", err)
	}

	got, err := svc.GetDASH(context.Background(), req)
	if err != nil {
		t.Fatalf("GetDASH returned error: %v", err)
	}
	if !bytes.Equal(got, want) {
		t.Fatalf("expected cached bytes %q, got %q", want, got)
	}
	if dashGen.calls != 0 {
		t.Fatalf("expected generator not called, got %d calls", dashGen.calls)
	}
}

func TestGetDASH_CacheMiss(t *testing.T) {
	svc, cacheMock, _, dashGen := setupManifestService(t)
	req := &model.ManifestRequest{AssetID: "asset-1"}
	key := cache.ManifestKey("dash", req.AssetID, req.FilterHash())

	got, err := svc.GetDASH(context.Background(), req)
	if err != nil {
		t.Fatalf("GetDASH returned error: %v", err)
	}
	if !bytes.Equal(got, dashGen.output) {
		t.Fatalf("expected generated bytes %q, got %q", dashGen.output, got)
	}
	if dashGen.calls != 1 {
		t.Fatalf("expected generator called once, got %d calls", dashGen.calls)
	}
	cached, err := cacheMock.Get(context.Background(), key)
	if err != nil {
		t.Fatalf("expected cached manifest, got error: %v", err)
	}
	if !bytes.Equal(cached, dashGen.output) {
		t.Fatalf("expected cached generated bytes %q, got %q", dashGen.output, cached)
	}
}

func TestGetHLS_DifferentFiltersDifferentCacheKeys(t *testing.T) {
	svc, _, hlsGen, _ := setupManifestService(t)
	reqA := &model.ManifestRequest{AssetID: "asset-1", Codec: "avc1"}
	reqB := &model.ManifestRequest{AssetID: "asset-1", Codec: "hvc1"}

	if _, err := svc.GetHLS(context.Background(), reqA); err != nil {
		t.Fatalf("GetHLS reqA returned error: %v", err)
	}
	if _, err := svc.GetHLS(context.Background(), reqB); err != nil {
		t.Fatalf("GetHLS reqB returned error: %v", err)
	}
	if hlsGen.calls != 2 {
		t.Fatalf("expected two generator calls for different filters, got %d", hlsGen.calls)
	}
}
