apiVersion: v1
kind: Secret
metadata:
  name: prism-secrets
  namespace: prism
  labels:
    app.kubernetes.io/name: prism
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: prism
type: Opaque
stringData:
  JWT_SECRET: "change-me-to-something-secure-min-32-chars"
  WIDEVINE_API_KEY: "your-widevine-api-key"
  FAIRPLAY_SECRET: "your-fairplay-secret"
  CLOUDFRONT_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIBVAIBADANBgkqhkiG9w0BAQEFAASCAT4wggE6AgEAAkEAqjPwLqKGxkFi53dv
    c8ywjTPKKnyFqrFr1kwVvNJzUR+zAm/gFnyVYC0lJMvV5cR41kO7ZvEZU72A42Im
    idNpZQIDAQABAkAqNGTbe4vF/5LB6NjnMxuYd/4qmOQgVoxyAD3nq5vSwozDM33i
    PJKWnuau4PXqlQBWBNWdVWqhLdFUpXk2FPfhAiEA32k79D9vZmUwvldTBz0PoIaD
    8+vxN/Y8w4MqxLBwG/kCIQDDB8SsUB70nOr1Vo8d1xWNnG5z8Lhk9JTpQYxvKtfb
    zQIgCEs+1413VETTb22MfotMxjfYNDkBJoO0s8lt0AmAz/kCID+1KemfwnzlRVsf
    C2EUAVZg4zO8Tn+r5XjMkLM/q4OBAiEA2h349/JHm08Sor0Ude2tM0yJ+6XauucI
    iTl48eFE6iQ=
    -----END PRIVATE KEY-----
