apiVersion: v1
kind: Service
metadata:
  name: prism
  namespace: prism
  labels:
    app.kubernetes.io/name: prism
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: prism
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: prism
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
