apiVersion: v1
kind: ServiceAccount
metadata:
  name: prism
  namespace: prism
  labels:
    app.kubernetes.io/name: prism
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: prism
automountServiceAccountToken: false
